# Generated by Django 5.1.15 on 2026-06-22 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre del equipo')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='Apellido')),
                ('dni', models.CharField(blank=True, max_length=15, verbose_name='DNI')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('steam_id', models.CharField(blank=True, max_length=60, verbose_name='Steam ID')),
                ('nick', models.CharField(blank=True, max_length=60, verbose_name='Nick / usuario')),
                ('gaming_center', models.CharField(blank=True, max_length=120, verbose_name='Gaming center')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre del torneo')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('game', models.CharField(choices=[('Dota 2', 'Dota 2'), ('Fortnite', 'Fortnite'), ('eFootball', 'eFootball'), ('Clash Royale', 'Clash Royale')], max_length=40, verbose_name='Juego')),
                ('format', models.CharField(choices=[('TEAM', 'Equipos'), ('DUO', 'Dúo'), ('SOLO', 'Individual')], default='TEAM', max_length=8, verbose_name='Formato')),
                ('team_size', models.PositiveSmallIntegerField(default=5, verbose_name='Jugadores por equipo')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('registration_close', models.DateTimeField(verbose_name='Cierre de inscripción')),
                ('prize_pen', models.PositiveIntegerField(default=0, verbose_name='Premio (S/)')),
                ('slots_total', models.PositiveIntegerField(default=32, verbose_name='Cupos')),
                ('slots_taken', models.PositiveIntegerField(default=0, verbose_name='Cupos ocupados')),
                ('status', models.CharField(choices=[('OPEN', 'Inscripciones abiertas'), ('FEW', 'Pocos cupos'), ('SOON', 'Próximamente')], default='OPEN', max_length=8, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Reglas / descripción')),
                ('featured', models.BooleanField(default=False, verbose_name='Torneo destacado')),
                ('code_prefix', models.CharField(default='BTD', max_length=8, verbose_name='Prefijo de código')),
                ('field_dni', models.BooleanField(default=True, verbose_name='Pedir DNI')),
                ('field_phone', models.BooleanField(default=True, verbose_name='Pedir teléfono')),
                ('field_email', models.BooleanField(default=True, verbose_name='Pedir correo')),
                ('field_steam', models.BooleanField(default=False, verbose_name='Pedir Steam ID')),
                ('field_nick', models.BooleanField(default=True, verbose_name='Pedir nick / usuario')),
                ('field_gaming_center', models.BooleanField(default=True, verbose_name='Pedir gaming center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=60, verbose_name='Nick')),
                ('steam_id', models.CharField(blank=True, max_length=60, verbose_name='Steam ID')),
                ('dni', models.CharField(blank=True, max_length=15, verbose_name='DNI')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.registration')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_label', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tournaments.registration')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament'),
        ),
    ]
